/**
 * Auto-extract per `git commit` — design pivot dalla white-list regex
 * (gh pr merge) a un'analisi LLM del diff vs i goal attivi dell'utente.
 *
 * Flow:
 *   1. PostToolUse hook intercetta Bash `git commit` (success only).
 *   2. Cattura il diff via `git show HEAD --no-color` (cap a N kB).
 *   3. Spawna l'LLM nativo dell'agent in background (`claude -p` per
 *      claude-code, `codex exec` per codex) con un prompt che gli dice
 *      di leggere `~/.deeplake/memory/goals/*.json`, filtrare ai goal
 *      dell'utente attivi, e bumpare qualunque KPI il diff abbia
 *      avanzato. Tutto detached, fire-and-forget.
 *   4. L'LLM scrive il file aggiornato → VFS → tabella memory →
 *      visibile al team al prossimo SessionStart.
 *
 * NO dedup commit→KPI in v1: se l'utente fa amend o se il commit-extract
 * gira due volte sullo stesso sha, il bump è doppio. L'utente lo
 * correggerà a mano editando il file.
 *
 * Env var `HIVEMIND_AUTO_KPI_FROM_COMMITS=false` disattiva globalmente.
 */

import { spawn } from "node:child_process";
import { execSync } from "node:child_process";

const ENV_DISABLE = "HIVEMIND_AUTO_KPI_FROM_COMMITS";
const DIFF_MAX_CHARS = 16_000; // cap for prompt size; bigger diffs get truncated with a marker

const GIT_COMMIT_RE = /^\s*git\s+commit\b/;

export interface CommitExtractInput {
  hook_event_name?: string;
  tool_name?: string;
  tool_input?: Record<string, unknown>;
  tool_response?: Record<string, unknown>;
}

export interface CommitExtractOptions {
  /** Agent identifier — picks the LLM CLI to spawn. */
  agent: "claude-code" | "codex" | "cursor" | "hermes" | string;
  /** user_email of the current Hivemind user. Used to scope goals. */
  currentUser: string;
  /** Optional explicit cwd (defaults to process.cwd()). */
  cwd?: string;
  /** Optional logger for tracing (defaults to no-op). */
  log?: (msg: string) => void;
}

/**
 * Returns true if the hook input is a successful `git commit` Bash
 * call. False otherwise — including when the env var disables the
 * feature.
 */
export function shouldExtract(input: CommitExtractInput): boolean {
  if (process.env[ENV_DISABLE] === "false" || process.env[ENV_DISABLE] === "0") {
    return false;
  }
  if (input.hook_event_name !== "PostToolUse") return false;
  if (input.tool_name !== "Bash") return false;
  const cmd = (input.tool_input as { command?: unknown } | undefined)?.command;
  if (typeof cmd !== "string") return false;
  if (!GIT_COMMIT_RE.test(cmd)) return false;
  return isSuccess(input.tool_response);
}

/**
 * Main entry — call this from the capture hook on every PostToolUse.
 * Returns immediately; the LLM work happens in a detached child
 * process. The function is safe to await but never blocks meaningfully
 * (the spawn itself is sync, the analysis is async outside our
 * process tree).
 *
 * Throws are intentionally not raised — any failure here must NOT
 * break the session-row INSERT. Caller can ignore the return value.
 */
export async function tryCommitKpiExtract(
  input: CommitExtractInput,
  options: CommitExtractOptions,
): Promise<"emitted" | "skipped" | "error"> {
  const log = options.log ?? (() => { /* noop */ });
  try {
    if (!shouldExtract(input)) return "skipped";

    const cwd = options.cwd ?? process.cwd();

    // git show HEAD — captures the just-committed diff. We pipe through
    // a char cap so a 5 MB autogenerated commit doesn't blow up the
    // prompt. Truncated diffs are marked so the LLM doesn't hallucinate
    // missing context.
    let diff = "";
    try {
      diff = execSync("git show HEAD --no-color --pretty=fuller", {
        cwd,
        encoding: "utf8",
        maxBuffer: 32 * 1024 * 1024,
        stdio: ["ignore", "pipe", "ignore"],
      });
    } catch (err: unknown) {
      log(`commit-kpi-extract: git show failed: ${(err as Error).message}`);
      return "error";
    }
    if (diff.length > DIFF_MAX_CHARS) {
      diff = diff.slice(0, DIFF_MAX_CHARS) + `\n\n[... diff truncated, original ${diff.length} chars ...]`;
    }

    const prompt = buildPrompt({
      currentUser: options.currentUser,
      diff,
    });

    const cli = cliForAgent(options.agent);
    if (!cli) {
      log(`commit-kpi-extract: no LLM CLI mapped for agent '${options.agent}', skipping`);
      return "skipped";
    }

    // Fire-and-forget. detached + unref so the worker survives the
    // hook exit, and stdio fully ignored so it doesn't keep the parent
    // alive. The LLM will read goal files via the VFS and rewrite the
    // relevant ones on its own.
    const child = spawn(cli.bin, [...cli.args, prompt], {
      cwd,
      detached: true,
      stdio: "ignore",
      env: process.env,
    });
    child.unref();
    log(`commit-kpi-extract: spawned ${cli.bin} pid=${child.pid}`);
    return "emitted";
  } catch (err: unknown) {
    (options.log ?? (() => { /* noop */ }))(`commit-kpi-extract: unexpected: ${(err as Error).message}`);
    return "error";
  }
}

interface CliSpec {
  bin: string;
  args: string[];
}

/**
 * Map the agent identifier to the right LLM CLI invocation. Each
 * agent uses its own credentials/plan — no Anthropic API key needed
 * in the plugin.
 *
 * Return null when the agent has no batch CLI we can dispatch to
 * (e.g. cursor/hermes/pi/openclaw don't currently ship one).
 */
function cliForAgent(agent: string): CliSpec | null {
  switch (agent) {
    case "claude-code":
    case "claude":
      return { bin: "claude", args: ["-p"] };
    case "codex":
      return {
        bin: "codex",
        args: ["exec", "--dangerously-bypass-approvals-and-sandbox", "-"],
      };
    default:
      return null;
  }
}

function buildPrompt(args: { currentUser: string; diff: string }): string {
  return [
    `A git commit just landed. Analyze the diff against the active goals owned by ${args.currentUser}.`,
    "",
    "Steps:",
    "1. List files in ~/.deeplake/memory/goals/ (each file is one goal in JSON).",
    `2. Read each file. Filter to those where assigned_to == "${args.currentUser}" AND status == "active".`,
    "3. For each matching goal, judge whether this commit advanced any of its KPIs. Be conservative — only count clear, direct evidence. If unsure, do NOTHING.",
    "4. If a KPI should be bumped: read the goal file again (in case it was edited concurrently), increment the matching KPI's `current` field, and write the complete JSON back to the same file path.",
    "5. Do NOT touch goals that don't match the diff. Do NOT modify `text`, `scope`, `assigned_to`, `assigned_by`, `goal_id`, or any other field except `current` of the affected KPI(s).",
    "",
    "Output nothing to stdout. The work is fire-and-forget; the user is not waiting.",
    "",
    "Commit diff:",
    "```",
    args.diff,
    "```",
  ].join("\n");
}

function isSuccess(tool_response: Record<string, unknown> | undefined): boolean {
  if (!tool_response) return true; // unknown shape — assume success
  if (tool_response.is_error === true) return false;
  if (tool_response.error && typeof tool_response.error === "string" && tool_response.error.length > 0) {
    return false;
  }
  if (tool_response.interrupted === true) return false;
  if (typeof tool_response.exit_code === "number" && tool_response.exit_code !== 0) return false;
  return true;
}
